# This is a basic workflow to help you get started with Actions

name: My-GitActioN
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello in testing 
        run : echo "Hello World from testing"
      - name: echo few commands
        run:
          echo "Hello me"
          echo "Aplication name ${{ env.APPLICATION_NAME }}"
  My-dep:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Print Hello
        run : echo "Hello World from deploy job" 
